/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var gramatica = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,4],$V1=[1,5],$V2=[1,6],$V3=[1,7],$V4=[1,8],$V5=[1,9],$V6=[1,10],$V7=[1,11],$V8=[1,12],$V9=[1,13],$Va=[1,14],$Vb=[1,15],$Vc=[1,16],$Vd=[1,18],$Ve=[1,19],$Vf=[1,20],$Vg=[1,21],$Vh=[1,23],$Vi=[5,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,26];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"INIT":3,"INSTRUCCION":4,"EOF":5,"INSTRUCCIONES":6,"WHILE":7,"DO_WHILE":8,"FOR":9,"IF":10,"ELSE_IF":11,"ELSE":12,"SWITCH":13,"PRINT":14,"PRINTLN":15,"METODO":16,"LLAMAR_METODO":17,"FUNCION":18,"LLAMAR_FUNCION":19,"PRIMITIVOS":20,"VECTORES":21,"BREAK":22,"CONTINUE":23,"RETURN":24,"DECLARACION":25,"TIPO_DATO":26,"Id_DECLARACION":27,"igual":28,"EXPRESION":29,"PuntoComa":30,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",7:"WHILE",8:"DO_WHILE",9:"FOR",10:"IF",11:"ELSE_IF",12:"ELSE",13:"SWITCH",14:"PRINT",15:"PRINTLN",16:"METODO",17:"LLAMAR_METODO",18:"FUNCION",19:"LLAMAR_FUNCION",21:"VECTORES",22:"BREAK",23:"CONTINUE",24:"RETURN",26:"TIPO_DATO",27:"Id_DECLARACION",28:"igual",29:"EXPRESION",30:"PuntoComa"},
productions_: [0,[3,2],[4,2],[4,1],[6,1],[6,1],[6,1],[6,1],[6,1],[6,1],[6,1],[6,1],[6,1],[6,1],[6,1],[6,1],[6,1],[6,1],[6,1],[6,1],[6,1],[6,1],[20,1],[25,5]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
console.log("termine analizar, recursiva por la derecha c:"); return $$[$0-1];
break;
case 2:
$$[$0-1].push($$[$0]); this.$=$$[$0-1];
break;
case 3:
this.$=[$$[$0]];
break;
case 4: case 5: case 6: case 7: case 8: case 9: case 10: case 11: case 12: case 13: case 14: case 15: case 16: case 17: case 18: case 19: case 20: case 21: case 22:
this.$=$$[$0];
break;
case 23:
this.$= new Declaracion();
break;
}
},
table: [{3:1,4:2,6:3,7:$V0,8:$V1,9:$V2,10:$V3,11:$V4,12:$V5,13:$V6,14:$V7,15:$V8,16:$V9,17:$Va,18:$Vb,19:$Vc,20:17,21:$Vd,22:$Ve,23:$Vf,24:$Vg,25:22,26:$Vh},{1:[3]},{5:[1,24],6:25,7:$V0,8:$V1,9:$V2,10:$V3,11:$V4,12:$V5,13:$V6,14:$V7,15:$V8,16:$V9,17:$Va,18:$Vb,19:$Vc,20:17,21:$Vd,22:$Ve,23:$Vf,24:$Vg,25:22,26:$Vh},o($Vi,[2,3]),o($Vi,[2,4]),o($Vi,[2,5]),o($Vi,[2,6]),o($Vi,[2,7]),o($Vi,[2,8]),o($Vi,[2,9]),o($Vi,[2,10]),o($Vi,[2,11]),o($Vi,[2,12]),o($Vi,[2,13]),o($Vi,[2,14]),o($Vi,[2,15]),o($Vi,[2,16]),o($Vi,[2,17]),o($Vi,[2,18]),o($Vi,[2,19]),o($Vi,[2,20]),o($Vi,[2,21]),o($Vi,[2,22]),{27:[1,26]},{1:[2,1]},o($Vi,[2,2]),{28:[1,27]},{29:[1,28]},{30:[1,29]},o($Vi,[2,23])],
defaultActions: {24:[2,1]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {"case-insensitive":true},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:
                console.log("reconoci el token <decimal> con lexema : "+yy_.yytext);
                return 'decimal';
                
break;
case 1:
                console.log("reconoci el token <entero> con lexema : "+yy_.yytext);
                return 'entero';
            
break;
case 2:
                console.log("reconoci el token <comentario> con lexema : "+yy_.yytext);
            
break;
case 3:
                    console.log("reconoci el token <comentarioMulti> con lexema : "+yy_.yytext);
                
break;
case 4:
                console.log("reconoci el token <coma> con lexema : "+yy_.yytext);
                return 'coma';
            
break;
case 5:
                console.log("reconoci el token <if> con lexema : "+yy_.yytext);
                return 'if';
            
break;
case 6:
                console.log("reconoci el token <else> con lexema : "+yy_.yytext);
                return 'else';
            
break;
case 7:
                console.log("reconoci el token <while> con lexema : "+yy_.yytext);
                return 'while';
            
break;
case 8:
                console.log("reconoci el token <for> con lexema : "+yy_.yytext);
                return 'for';
            
break;
case 9:
                console.log("reconoci el token <do> con lexema : "+yy_.yytext);
                return 'do';
            
break;
case 10:
                console.log("reconoci el token <break> con lexema : "+yy_.yytext);
                return 'break';
            
break;
case 11:
                console.log("reconoci el token <continue> con lexema : "+yy_.yytext);
                return 'continue';
            
break;
case 12:
                console.log("reconoci el token <void> con lexema : "+yy_.yytext);
                return 'void';
            
break;
case 13:
                console.log("reconoci el token <switch> con lexema : "+yy_.yytext);
                return 'switch';
            
break;
case 14:
                console.log("reconoci el token <case> con lexema : "+yy_.yytext);
                return 'case';
            
break;
case 15:
                console.log("reconoci el token <default> con lexema : "+yy_.yytext);
                return 'default';
            
break;
case 16:
                console.log("reconoci el token <Println> con lexema : "+yy_.yytext);
                return 'Println';
            
break;
case 17:
                console.log("reconoci el token <Print> con lexema : "+yy_.yytext);
                return 'Print';
            
break;
case 18:
                console.log("reconoci el token <toLower> con lexema : "+yy_.yytext);
                return 'toLower';
            
break;
case 19:
                console.log("reconoci el token <toUpper> con lexema : "+yy_.yytext);
                return 'toUpper';
            
break;
case 20:
                console.log("reconoci el token <round> con lexema : "+yy_.yytext);
                return 'round';
            
break;
case 21:
                console.log("reconoci el token <length> con lexema : "+yy_.yytext);
                return 'length';
            
break;
case 22:
                console.log("reconoci el token <typeof> con lexema : "+yy_.yytext);
                return 'typeof';
            
break;
case 23:
                console.log("reconoci el token <toString> con lexema : "+yy_.yytext);
                return 'ToString';
            
break;
case 24:
                console.log("reconoci el token <toCharArray> con lexema : "+yy_.yytext);
                return 'toCharArray';
            
break;
case 25:
                console.log("reconoci el token <run> con lexema : "+yy_.yytext);
                return 'run';
               
break;
case 26:
                console.log("reconoci el token <new> con lexema : "+yy_.yytext);
                return 'new';
               
break;
case 27:
                console.log("reconoci el token <int> con lexema : "+yy_.yytext);
                return 'int';
               
break;
case 28:
                console.log("reconoci el token <run> con lexema : "+yy_.yytext);
                return 'double';
               
break;
case 29:
                console.log("reconoci el token <run> con lexema : "+yy_.yytext);
                return 'char';
               
break;
case 30:
                console.log("reconoci el token <run> con lexema : "+yy_.yytext);
                return 'boolean';
               
break;
case 31:
                console.log("reconoci el token <run> con lexema : "+yy_.yytext);
                return 'String';
               
break;
case 32:
                console.log("reconoci el token <true> con lexema : "+yy_.yytext);
                return 'True';
               
break;
case 33:
                console.log("reconoci el token <false> con lexema : "+yy_.yytext);
                return 'False';
               
break;
case 34:
                console.log("reconoci el token <DosPuntos> con lexema : "+yy_.yytext);
                return 'DosPuntos';
            
break;
case 35:
                console.log("reconoci el token <PuntoComa> con lexema : "+yy_.yytext);
                return 30;
            
break;
case 36:
                console.log("reconoci el token <ParentesisA> con lexema : "+yy_.yytext);
                return 'ParentesisA';
            
break;
case 37:
                console.log("reconoci el token <ParentesisC> con lexema : "+yy_.yytext);
                return 'ParentesisC';
            
break;
case 38:
                console.log("reconoci el token <CorcheteA> con lexema : "+yy_.yytext);
                return 'CorcheteA';
            
break;
case 39:
                console.log("reconoci el token <CorcheteC> con lexema : "+yy_.yytext);
                return 'CorcheteC';
            
break;
case 40:
                console.log("reconoci el token <LlaveA> con lexema : "+yy_.yytext);
                return 'LlaveA';
            
break;
case 41:
                console.log("reconoci el token <LlaveC> con lexema : "+yy_.yytext);
                return 'LlaveC';
            
break;
case 42:
                console.log("reconoci el token <mas> con lexema : "+yy_.yytext);
                return 'mas';
            
break;
case 43:
                console.log("reconoci el token <menos> con lexema : "+yy_.yytext);
                return 'menos';
            
break;
case 44:
                console.log("reconoci el token <multiplicacion> con lexema : "+yy_.yytext);
                return 'multiplicacion';
            
break;
case 45:
                console.log("reconoci el token <division> con lexema : "+yy_.yytext);
                return 'division';
            
break;
case 46:
                console.log("reconoci el token <potencia> con lexema : "+yy_.yytext);
                return 'potencia';
            
break;
case 47:
                console.log("reconoci el token <modulo> con lexema : "+yy_.yytext);
                return 'modulo';
            
break;
case 48:
                console.log("reconoci el token <igualIf> con lexema : "+yy_.yytext);
                return 'igualIf';
            
break;
case 49:
                console.log("reconoci el token <igual> con lexema : "+yy_.yytext);
                return 28;
            
break;
case 50:
                console.log("reconoci el token <desIgual> con lexema : "+yy_.yytext);
                return 'desIgual';
            
break;
case 51:
                console.log("reconoci el token <menor> con lexema : "+yy_.yytext);
                return 'menor';
            
break;
case 52:
                console.log("reconoci el token <menorIgual> con lexema : "+yy_.yytext);
                return 'menorIgual';
            
break;
case 53:
                console.log("reconoci el token <mayor> con lexema : "+yy_.yytext);
                return 'mayor';
            
break;
case 54:
                console.log("reconoci el token <mayorIgual> con lexema : "+yy_.yytext);
                return 'mayorIgual';
            
break;
case 55:
                console.log("reconoci el token <Interrogacion> con lexema : "+yy_.yytext);
                return 'InterrogacionC';
            
break;
case 56:
                console.log("reconoci el token <or> con lexema : "+yy_.yytext);
                return 'or';
            
break;
case 57:
                console.log("reconoci el token <and> con lexema : "+yy_.yytext);
                return 'and';
            
break;
case 58:
                console.log("reconoci el token <not> con lexema : "+yy_.yytext);
                return 'not';
            
break;
case 59:
                                                console.log("reconoci el token <cadena> con lexema : "+yy_.yytext);
                                                return 'cadena';
                                            
break;
case 60:
                                                console.log("reconoci el token <cadena> con lexema : "+yy_.yytext);
                                                return 'cadena';
                                            
break;
case 61:
                            console.log("reconoci el token <id> con lexema : "+yy_.yytext);
                            return 'id';
                            
break;
case 62:
break;
case 63:
break;
case 64:
break;
case 65:
break;
case 66:return 5;
break;
case 67:
                console.log('Este es un error lexico : '+yy_.yytext+", en la linea : "+yy_.yylloc.first_line+", columna : "+yy_.yylloc.fisrt_column);
            
break;
}
},
rules: [/^(?:[0-9]+\.[0-9]+)/i,/^(?:[0-9]+)/i,/^(?:\/\/[^\n]*)/i,/^(?:\/\*[^"*/"]*\*\/)/i,/^(?:,)/i,/^(?:if\b)/i,/^(?:else\b)/i,/^(?:while\b)/i,/^(?:for\b)/i,/^(?:do\b)/i,/^(?:break\b)/i,/^(?:continue\b)/i,/^(?:void\b)/i,/^(?:switch\b)/i,/^(?:case\b)/i,/^(?:default\b)/i,/^(?:Println\b)/i,/^(?:Print\b)/i,/^(?:toLower\b)/i,/^(?:toUpper\b)/i,/^(?:round\b)/i,/^(?:length\b)/i,/^(?:typeof\b)/i,/^(?:toString\b)/i,/^(?:toCharArray\b)/i,/^(?:run\b)/i,/^(?:new\b)/i,/^(?:int\b)/i,/^(?:double\b)/i,/^(?:char\b)/i,/^(?:boolean\b)/i,/^(?:string\b)/i,/^(?:true\b)/i,/^(?:false\b)/i,/^(?::)/i,/^(?:;)/i,/^(?:\()/i,/^(?:\))/i,/^(?:\[)/i,/^(?:\])/i,/^(?:\{)/i,/^(?:\})/i,/^(?:\+)/i,/^(?:-)/i,/^(?:\*)/i,/^(?:\/)/i,/^(?:\^)/i,/^(?:%)/i,/^(?:==)/i,/^(?:=)/i,/^(?:!=)/i,/^(?:<)/i,/^(?:<=)/i,/^(?:>)/i,/^(?:>=)/i,/^(?:\?)/i,/^(?:\|\|)/i,/^(?:&&)/i,/^(?:!)/i,/^(?:'[^\']*')/i,/^(?:"[^\"]*")/i,/^(?:([a-zA-ZñÑ])[a-zA-ZñÑ0-9_]*)/i,/^(?:\t)/i,/^(?:\r)/i,/^(?:\n)/i,/^(?:\s)/i,/^(?:$)/i,/^(?:.)/i],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = gramatica;
exports.Parser = gramatica.Parser;
exports.parse = function () { return gramatica.parse.apply(gramatica, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}